name: chiletv
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.7
  - argh=0.26
  - tqdm=4.61
  - ffmpeg=4.3
  - numpy=1.19
  - matplotlib=3.5
  - seaborn=0.11
  - py-opencv=4.5
  - pytorch=1.10
  - torchvision=0.11
  - scrapy=2.4
  - spacy=3.1
  - jupyterlab=3.3
  - notebook=6.4
  - scipy=1.7
  - pandas=1.3
  - pip=20.3
  - pip:
      - youtube-dl
      - facenet-pytorch==2.5.*